"""
Email Service Module

This module handles sending LinkedIn post drafts via email.

Why this file exists:
- Delivers generated posts to your inbox
- Formats emails professionally with HTML
- Handles SMTP connection and error handling
- Provides retry logic for reliability

How it works:
1. Takes a LinkedInPost object
2. Formats it into an HTML email
3. Connects to SMTP server (Gmail)
4. Sends email with the post draft
5. Handles errors gracefully

Email Format:
- Subject: AI News Post - [Article Title]
- Body: HTML formatted with post content and metadata
- Includes: Source article link, post stats, copy-paste ready text
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from models import LinkedInPost
from config import config
from utils import get_logger

logger = get_logger(__name__)


class EmailService:
    """
    Sends LinkedIn post drafts via email using SMTP.
    """

    def __init__(self):
        """Initialize the email service with configuration."""
        self.smtp_server = config.SMTP_SERVER
        self.smtp_port = config.SMTP_PORT
        self.sender_email = config.SENDER_EMAIL
        self.sender_password = config.SENDER_PASSWORD
        self.receiver_email = config.RECEIVER_EMAIL

        # Validate configuration
        if not all([self.sender_email, self.sender_password, self.receiver_email]):
            raise ValueError("Email configuration incomplete. Check .env file.")

    def send_post(self, post: LinkedInPost) -> bool:
        """
        Send a LinkedIn post draft via email.

        Args:
            post: LinkedInPost object to send

        Returns:
            True if sent successfully, False otherwise
        """
        logger.info(f"Sending email to {self.receiver_email}")

        try:
            # Create email message
            message = self._create_email_message(post)

            # Send via SMTP
            self._send_via_smtp(message)

            logger.info("Email sent successfully")
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP authentication failed. Check email credentials.")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {str(e)}")
            return False
        except Exception as e:
            logger.error(f"Failed to send email: {str(e)}", exc_info=True)
            return False

    def _create_email_message(self, post: LinkedInPost) -> MIMEMultipart:
        """
        Create a formatted email message.

        Args:
            post: LinkedInPost to format

        Returns:
            MIMEMultipart email message
        """
        # Create message container
        message = MIMEMultipart("alternative")
        message["Subject"] = f"AI News Post - {post.source_article.title[:50]}..."
        message["From"] = self.sender_email
        message["To"] = self.receiver_email

        # Create plain text version
        text_content = self._format_text_email(post)

        # Create HTML version
        html_content = self._format_html_email(post)

        # Attach both versions
        part1 = MIMEText(text_content, "plain")
        part2 = MIMEText(html_content, "html")

        message.attach(part1)
        message.attach(part2)

        return message

    def _format_text_email(self, post: LinkedInPost) -> str:
        """
        Format post as plain text email.

        Args:
            post: LinkedInPost to format

        Returns:
            Plain text email content
        """
        article = post.source_article

        return f"""
AI News Content Agent
Generated: {post.generated_date.strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
LINKEDIN POST DRAFT
{'='*60}

{post.format_for_linkedin()}

{'='*60}
SOURCE ARTICLE
{'='*60}

Title: {article.title}
Source: {article.source}
URL: {article.url}
Published: {article.published_date.strftime('%Y-%m-%d %H:%M:%S')}
Score: {article.score}/100

Summary:
{article.summary}

{'='*60}
POST STATISTICS
{'='*60}

Word Count: {post.word_count()} words
Hashtags: {len(post.hashtags)}
Generated by: AI News Content Agent

{'='*60}

Ready to post on LinkedIn!
Simply copy the post content above and paste it into LinkedIn.
        """.strip()

    def _format_html_email(self, post: LinkedInPost) -> str:
        """
        Format post as HTML email.

        Args:
            post: LinkedInPost to format

        Returns:
            HTML email content
        """
        article = post.source_article

        # Format the post with line breaks
        formatted_post = post.format_for_linkedin().replace('\n', '<br>')

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background-color: #0077b5;
            color: white;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }}
        .post-container {{
            background-color: #f8f9fa;
            border-left: 4px solid #0077b5;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .post-content {{
            font-size: 16px;
            line-height: 1.8;
            white-space: pre-wrap;
        }}
        .metadata {{
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .stats {{
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
        }}
        .stat-item {{
            text-align: center;
        }}
        .stat-value {{
            font-size: 24px;
            font-weight: bold;
            color: #0077b5;
        }}
        .stat-label {{
            font-size: 12px;
            color: #666;
        }}
        .button {{
            display: inline-block;
            background-color: #0077b5;
            color: white;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px 0;
        }}
        .footer {{
            text-align: center;
            color: #666;
            font-size: 12px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }}
        a {{
            color: #0077b5;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0;">🤖 AI News Content Agent</h1>
        <p style="margin: 5px 0 0 0;">Your Daily LinkedIn Post is Ready!</p>
    </div>

    <div class="post-container">
        <h2 style="margin-top: 0; color: #0077b5;">LinkedIn Post Draft</h2>
        <div class="post-content">{formatted_post}</div>
    </div>

    <div class="stats">
        <div class="stat-item">
            <div class="stat-value">{post.word_count()}</div>
            <div class="stat-label">WORDS</div>
        </div>
        <div class="stat-item">
            <div class="stat-value">{len(post.hashtags)}</div>
            <div class="stat-label">HASHTAGS</div>
        </div>
        <div class="stat-item">
            <div class="stat-value">{article.score:.0f}</div>
            <div class="stat-label">RELEVANCE SCORE</div>
        </div>
    </div>

    <div class="metadata">
        <h3 style="margin-top: 0; color: #0077b5;">Source Article</h3>
        <p><strong>Title:</strong> {article.title}</p>
        <p><strong>Source:</strong> {article.source}</p>
        <p><strong>Published:</strong> {article.published_date.strftime('%B %d, %Y at %I:%M %p')}</p>
        <p><strong>URL:</strong> <a href="{article.url}" target="_blank">{article.url}</a></p>

        <h4 style="color: #0077b5;">Summary:</h4>
        <p>{article.summary}</p>
    </div>

    <div style="text-align: center; margin: 30px 0;">
        <a href="https://www.linkedin.com/feed/" class="button" target="_blank">
            Post to LinkedIn →
        </a>
    </div>

    <div class="footer">
        <p>Generated on {post.generated_date.strftime('%B %d, %Y at %I:%M %p')}</p>
        <p>Powered by AI News Content Agent | Using Google Gemini AI</p>
    </div>
</body>
</html>
        """

        return html

    def _send_via_smtp(self, message: MIMEMultipart) -> None:
        """
        Send email via SMTP.

        Args:
            message: Email message to send

        Raises:
            Various SMTP exceptions on failure
        """
        logger.debug(f"Connecting to SMTP server: {self.smtp_server}:{self.smtp_port}")

        # Create SMTP connection
        with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
            server.set_debuglevel(0)  # Set to 1 for verbose SMTP debugging

            # Start TLS encryption
            server.starttls()
            logger.debug("TLS connection established")

            # Login
            server.login(self.sender_email, self.sender_password)
            logger.debug("SMTP authentication successful")

            # Send email
            server.send_message(message)
            logger.debug("Email sent via SMTP")

    def send_test_email(self) -> bool:
        """
        Send a test email to verify configuration.

        Returns:
            True if sent successfully, False otherwise
        """
        logger.info("Sending test email")

        try:
            message = MIMEMultipart("alternative")
            message["Subject"] = "AI News Agent - Test Email"
            message["From"] = self.sender_email
            message["To"] = self.receiver_email

            text = """
AI News Content Agent - Test Email

This is a test email to verify your email configuration is working correctly.

If you received this email, your SMTP settings are configured properly!

Configuration:
- SMTP Server: {server}
- SMTP Port: {port}
- Sender: {sender}
- Receiver: {receiver}

You're all set to receive daily LinkedIn post drafts!
            """.format(
                server=self.smtp_server,
                port=self.smtp_port,
                sender=self.sender_email,
                receiver=self.receiver_email
            ).strip()

            html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background-color: #28a745;
            color: white;
            padding: 20px;
            border-radius: 5px;
            text-align: center;
        }}
        .content {{
            padding: 20px;
            background-color: #f8f9fa;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .success {{
            color: #28a745;
            font-size: 48px;
            text-align: center;
            margin: 20px 0;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0;">🤖 AI News Content Agent</h1>
        <p style="margin: 5px 0 0 0;">Test Email</p>
    </div>

    <div class="success">✓</div>

    <div class="content">
        <h2 style="color: #28a745;">Email Configuration Working!</h2>
        <p>This is a test email to verify your email configuration is working correctly.</p>
        <p>If you received this email, your SMTP settings are configured properly!</p>

        <h3>Configuration:</h3>
        <ul>
            <li><strong>SMTP Server:</strong> {self.smtp_server}</li>
            <li><strong>SMTP Port:</strong> {self.smtp_port}</li>
            <li><strong>Sender:</strong> {self.sender_email}</li>
            <li><strong>Receiver:</strong> {self.receiver_email}</li>
        </ul>

        <p style="color: #28a745; font-weight: bold;">✓ You're all set to receive daily LinkedIn post drafts!</p>
    </div>
</body>
</html>
            """

            part1 = MIMEText(text, "plain")
            part2 = MIMEText(html, "html")
            message.attach(part1)
            message.attach(part2)

            self._send_via_smtp(message)

            logger.info("Test email sent successfully")
            return True

        except Exception as e:
            logger.error(f"Failed to send test email: {str(e)}", exc_info=True)
            return False
