"""
Email Service Module

This module handles sending LinkedIn post drafts via email.

Why this file exists:
- Delivers generated posts to your inbox
- Formats emails professionally with HTML
- Handles SMTP connection and error handling
- Provides retry logic for reliability

How it works:
1. Takes a LinkedInPost object
2. Formats it into an HTML email
3. Connects to SMTP server (Gmail)
4. Sends email with the post draft
5. Handles errors gracefully

Email Format:
- Subject: AI News Post - [Article Title]
- Body: HTML formatted with post content and metadata
- Includes: Source article link, post stats, copy-paste ready text
"""

import smtplib
import html
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from models import LinkedInPost, IntelligenceBrief
from config import config
from utils import get_logger

logger = get_logger(__name__)


class EmailService:
    """
    Sends LinkedIn post drafts via email using SMTP.
    """

    def __init__(self):
        """Initialize the email service with configuration."""
        self.smtp_server = config.SMTP_SERVER
        self.smtp_port = config.SMTP_PORT
        self.sender_email = config.SENDER_EMAIL
        self.sender_password = config.SENDER_PASSWORD
        self.receiver_email = config.RECEIVER_EMAIL

        # Validate configuration
        if not all([self.sender_email, self.sender_password, self.receiver_email]):
            raise ValueError("Email configuration incomplete. Check .env file.")

    def send_post(self, post: LinkedInPost) -> bool:
        """
        Send a LinkedIn post draft via email.

        Args:
            post: LinkedInPost object to send

        Returns:
            True if sent successfully, False otherwise
        """
        logger.info(f"Sending email to {self.receiver_email}")

        try:
            # Create email message
            message = self._create_email_message(post)

            # Send via SMTP
            self._send_via_smtp(message)

            logger.info("Email sent successfully")
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP authentication failed. Check email credentials.")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {str(e)}")
            return False
        except Exception as e:
            logger.error(f"Failed to send email: {str(e)}", exc_info=True)
            return False

    def _create_email_message(self, post: LinkedInPost) -> MIMEMultipart:
        """
        Create a formatted email message.

        Args:
            post: LinkedInPost to format

        Returns:
            MIMEMultipart email message
        """
        # Create message container
        message = MIMEMultipart("alternative")
        message["Subject"] = f"AI News Post - {post.source_article.title[:50]}..."
        message["From"] = self.sender_email
        message["To"] = self.receiver_email

        # Create plain text version
        text_content = self._format_text_email(post)

        # Create HTML version
        html_content = self._format_html_email(post)

        # Attach both versions
        part1 = MIMEText(text_content, "plain")
        part2 = MIMEText(html_content, "html")

        message.attach(part1)
        message.attach(part2)

        return message

    def _format_text_email(self, post: LinkedInPost) -> str:
        """
        Format post as plain text email.

        Args:
            post: LinkedInPost to format

        Returns:
            Plain text email content
        """
        article = post.source_article

        return f"""
AI News Content Agent
Generated: {post.generated_date.strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
LINKEDIN POST DRAFT
{'='*60}

{post.format_for_linkedin()}

{'='*60}
SOURCE ARTICLE
{'='*60}

Title: {article.title}
Source: {article.source}
URL: {article.url}
Published: {article.published_date.strftime('%Y-%m-%d %H:%M:%S')}
Score: {article.score}/100

Summary:
{article.summary}

{'='*60}
POST STATISTICS
{'='*60}

Word Count: {post.word_count()} words
Hashtags: {len(post.hashtags)}
Generated by: AI News Content Agent

{'='*60}

Ready to post on LinkedIn!
Simply copy the post content above and paste it into LinkedIn.
        """.strip()

    def _format_html_email(self, post: LinkedInPost) -> str:
        """
        Format post as HTML email.

        Args:
            post: LinkedInPost to format

        Returns:
            HTML email content
        """
        article = post.source_article

        # Format the post with line breaks
        formatted_post = post.format_for_linkedin().replace('\n', '<br>')

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background-color: #0077b5;
            color: white;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }}
        .post-container {{
            background-color: #f8f9fa;
            border-left: 4px solid #0077b5;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .post-content {{
            font-size: 16px;
            line-height: 1.8;
            white-space: pre-wrap;
        }}
        .metadata {{
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .stats {{
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
        }}
        .stat-item {{
            text-align: center;
        }}
        .stat-value {{
            font-size: 24px;
            font-weight: bold;
            color: #0077b5;
        }}
        .stat-label {{
            font-size: 12px;
            color: #666;
        }}
        .button {{
            display: inline-block;
            background-color: #0077b5;
            color: white;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px 0;
        }}
        .footer {{
            text-align: center;
            color: #666;
            font-size: 12px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }}
        a {{
            color: #0077b5;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0;">🤖 AI News Content Agent</h1>
        <p style="margin: 5px 0 0 0;">Your Daily LinkedIn Post is Ready!</p>
    </div>

    <div class="post-container">
        <h2 style="margin-top: 0; color: #0077b5;">LinkedIn Post Draft</h2>
        <div class="post-content">{formatted_post}</div>
    </div>

    <div class="stats">
        <div class="stat-item">
            <div class="stat-value">{post.word_count()}</div>
            <div class="stat-label">WORDS</div>
        </div>
        <div class="stat-item">
            <div class="stat-value">{len(post.hashtags)}</div>
            <div class="stat-label">HASHTAGS</div>
        </div>
        <div class="stat-item">
            <div class="stat-value">{article.score:.0f}</div>
            <div class="stat-label">RELEVANCE SCORE</div>
        </div>
    </div>

    <div class="metadata">
        <h3 style="margin-top: 0; color: #0077b5;">Source Article</h3>
        <p><strong>Title:</strong> {article.title}</p>
        <p><strong>Source:</strong> {article.source}</p>
        <p><strong>Published:</strong> {article.published_date.strftime('%B %d, %Y at %I:%M %p')}</p>
        <p><strong>URL:</strong> <a href="{article.url}" target="_blank">{article.url}</a></p>

        <h4 style="color: #0077b5;">Summary:</h4>
        <p>{article.summary}</p>
    </div>

    <div style="text-align: center; margin: 30px 0;">
        <a href="https://www.linkedin.com/feed/" class="button" target="_blank">
            Post to LinkedIn →
        </a>
    </div>

    <div class="footer">
        <p>Generated on {post.generated_date.strftime('%B %d, %Y at %I:%M %p')}</p>
        <p>Powered by AI News Content Agent | Using Google Gemini AI</p>
    </div>
</body>
</html>
        """

        return html

    def _send_via_smtp(self, message: MIMEMultipart) -> None:
        """
        Send email via SMTP.

        Args:
            message: Email message to send

        Raises:
            Various SMTP exceptions on failure
        """
        logger.debug(f"Connecting to SMTP server: {self.smtp_server}:{self.smtp_port}")

        # Create SMTP connection
        with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
            server.set_debuglevel(0)  # Set to 1 for verbose SMTP debugging

            # Start TLS encryption
            server.starttls()
            logger.debug("TLS connection established")

            # Login
            server.login(self.sender_email, self.sender_password)
            logger.debug("SMTP authentication successful")

            # Send email
            server.send_message(message)
            logger.debug("Email sent via SMTP")

    def send_test_email(self) -> bool:
        """
        Send a test email to verify configuration.

        Returns:
            True if sent successfully, False otherwise
        """
        logger.info("Sending test email")

        try:
            message = MIMEMultipart("alternative")
            message["Subject"] = "AI News Agent - Test Email"
            message["From"] = self.sender_email
            message["To"] = self.receiver_email

            text = """
AI News Content Agent - Test Email

This is a test email to verify your email configuration is working correctly.

If you received this email, your SMTP settings are configured properly!

Configuration:
- SMTP Server: {server}
- SMTP Port: {port}
- Sender: {sender}
- Receiver: {receiver}

You're all set to receive daily LinkedIn post drafts!
            """.format(
                server=self.smtp_server,
                port=self.smtp_port,
                sender=self.sender_email,
                receiver=self.receiver_email
            ).strip()

            html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background-color: #28a745;
            color: white;
            padding: 20px;
            border-radius: 5px;
            text-align: center;
        }}
        .content {{
            padding: 20px;
            background-color: #f8f9fa;
            margin: 20px 0;
            border-radius: 5px;
        }}
        .success {{
            color: #28a745;
            font-size: 48px;
            text-align: center;
            margin: 20px 0;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0;">🤖 AI News Content Agent</h1>
        <p style="margin: 5px 0 0 0;">Test Email</p>
    </div>

    <div class="success">✓</div>

    <div class="content">
        <h2 style="color: #28a745;">Email Configuration Working!</h2>
        <p>This is a test email to verify your email configuration is working correctly.</p>
        <p>If you received this email, your SMTP settings are configured properly!</p>

        <h3>Configuration:</h3>
        <ul>
            <li><strong>SMTP Server:</strong> {self.smtp_server}</li>
            <li><strong>SMTP Port:</strong> {self.smtp_port}</li>
            <li><strong>Sender:</strong> {self.sender_email}</li>
            <li><strong>Receiver:</strong> {self.receiver_email}</li>
        </ul>

        <p style="color: #28a745; font-weight: bold;">✓ You're all set to receive daily LinkedIn post drafts!</p>
    </div>
</body>
</html>
            """

            part1 = MIMEText(text, "plain")
            part2 = MIMEText(html, "html")
            message.attach(part1)
            message.attach(part2)

            self._send_via_smtp(message)

            logger.info("Test email sent successfully")
            return True

        except Exception as e:
            logger.error(f"Failed to send test email: {str(e)}", exc_info=True)
            return False

    # ========================================================================
    # V1 Methods - Intelligence Brief Email
    # ========================================================================

    def send_intelligence_brief(self, brief: IntelligenceBrief) -> bool:
        """
        Send an intelligence brief via email.

        Args:
            brief: IntelligenceBrief object to send

        Returns:
            True if sent successfully, False otherwise
        """
        logger.info(f"Sending intelligence brief to {self.receiver_email}")

        try:
            # Create email message
            message = self._create_brief_email_message(brief)

            # Send via SMTP
            self._send_via_smtp(message)

            logger.info("Intelligence brief email sent successfully")
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP authentication failed. Check email credentials.")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {str(e)}")
            return False
        except Exception as e:
            logger.error(f"Failed to send intelligence brief email: {str(e)}", exc_info=True)
            return False

    def _create_brief_email_message(self, brief: IntelligenceBrief) -> MIMEMultipart:
        """
        Create a formatted email message for intelligence brief.

        Args:
            brief: IntelligenceBrief to format

        Returns:
            MIMEMultipart email message
        """
        # Create message container
        message = MIMEMultipart("alternative")
        message["Subject"] = f"AI Competitive Intelligence Brief - {brief.period_start.strftime('%b %d')} to {brief.period_end.strftime('%b %d, %Y')}"
        message["From"] = self.sender_email
        message["To"] = self.receiver_email

        # Create plain text version
        text_content = self._format_brief_text_email(brief)

        # Create HTML version
        html_content = self._format_brief_html_email(brief)

        # Attach both versions
        part1 = MIMEText(text_content, "plain")
        part2 = MIMEText(html_content, "html")

        message.attach(part1)
        message.attach(part2)

        return message

    def _format_brief_text_email(self, brief: IntelligenceBrief) -> str:
        """
        Format brief as plain text email.

        Args:
            brief: IntelligenceBrief to format

        Returns:
            Plain text email content
        """
        return f"""
AI Competitive Intelligence Brief
Generated: {brief.generated_at.strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
REPORTING PERIOD
{'='*60}

{brief.period_start.strftime('%B %d, %Y')} to {brief.period_end.strftime('%B %d, %Y')}
Total Findings: {brief.finding_count}

{'='*60}
EXECUTIVE SUMMARY
{'='*60}

{brief.executive_summary}

{'='*60}
KEY FINDINGS
{'='*60}

{self._format_key_findings_text(brief.key_findings)}

{'='*60}
COMPETITOR ACTIVITY
{'='*60}

{self._format_competitor_activity_text(brief.competitor_activity)}

{'='*60}

Powered by AI Competitive Intelligence Worker V1
        """.strip()

    def _format_key_findings_text(self, key_findings: list) -> str:
        """Format key findings as text."""
        lines = []
        for i, finding in enumerate(key_findings, 1):
            lines.append(f"{i}. {finding['text']}")
            lines.append(f"   Source: {finding['source_name']}")
            lines.append(f"   URL: {finding['source_url']}")
            lines.append("")
        return "\n".join(lines)

    def _format_competitor_activity_text(self, competitor_activity: dict) -> str:
        """Format competitor activity as text."""
        lines = []
        for competitor in sorted(competitor_activity.keys()):
            activities = competitor_activity[competitor]
            lines.append(f"\n{competitor}:")
            for activity in activities:
                lines.append(f"  • {activity['text']}")
                lines.append(f"    Source: {activity['source_name']}")
                lines.append(f"    URL: {activity['source_url']}")
            lines.append("")
        return "\n".join(lines)

    def _format_brief_html_email(self, brief: IntelligenceBrief) -> str:
        """
        Format brief as HTML email.

        Args:
            brief: IntelligenceBrief to format

        Returns:
            HTML email content
        """
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .stats {{
            display: flex;
            justify-content: space-around;
            margin: 20px 0 30px 0;
        }}
        .stat-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            flex: 1;
            margin: 0 10px;
        }}
        .stat-value {{
            font-size: 32px;
            font-weight: bold;
            color: #667eea;
        }}
        .stat-label {{
            font-size: 14px;
            color: #666;
            margin-top: 5px;
        }}
        .section {{
            background: white;
            padding: 25px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            margin-top: 0;
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .finding-item {{
            margin-bottom: 20px;
            padding: 15px;
            background: #f8f9fa;
            border-left: 4px solid #667eea;
            border-radius: 4px;
        }}
        .finding-text {{
            margin-bottom: 10px;
            font-size: 16px;
        }}
        .finding-source {{
            font-size: 13px;
            color: #666;
        }}
        .finding-source a {{
            color: #667eea;
            text-decoration: none;
        }}
        .finding-source a:hover {{
            text-decoration: underline;
        }}
        .competitor-section {{
            margin-bottom: 25px;
        }}
        .competitor-name {{
            font-size: 20px;
            font-weight: bold;
            color: #764ba2;
            margin-bottom: 15px;
        }}
        .activity-item {{
            margin-bottom: 15px;
            padding-left: 20px;
            border-left: 3px solid #ddd;
        }}
        .footer {{
            text-align: center;
            color: #666;
            font-size: 12px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🎯 AI Competitive Intelligence Brief</h1>
        <p>{brief.period_start.strftime('%B %d')} - {brief.period_end.strftime('%B %d, %Y')}</p>
    </div>

    <div class="stats">
        <div class="stat-card">
            <div class="stat-value">{brief.finding_count}</div>
            <div class="stat-label">TOTAL FINDINGS</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(brief.competitor_activity)}</div>
            <div class="stat-label">COMPETITORS</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(brief.key_findings)}</div>
            <div class="stat-label">KEY FINDINGS</div>
        </div>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>{html.escape(brief.executive_summary)}</p>
    </div>

    <div class="section">
        <h2>Key Findings</h2>
        {self._format_key_findings_html(brief.key_findings)}
    </div>

    <div class="section">
        <h2>Competitor Activity</h2>
        {self._format_competitor_activity_html(brief.competitor_activity)}
    </div>

    <div class="footer">
        <p>Generated on {brief.generated_at.strftime('%B %d, %Y at %I:%M %p')}</p>
        <p>Powered by AI Competitive Intelligence Worker V1 | Using Google Gemini AI</p>
    </div>
</body>
</html>
        """

        return html_content

    def _format_key_findings_html(self, key_findings: list) -> str:
        """Format key findings as HTML."""
        html_items = []
        for i, finding in enumerate(key_findings, 1):
            # Escape all untrusted content
            finding_text = html.escape(finding.get('text', ''))
            source_name = html.escape(finding.get('source_name', ''))
            source_url = html.escape(finding.get('source_url', ''), quote=True)

            html_items.append(f"""
        <div class="finding-item">
            <div class="finding-text"><strong>{i}.</strong> {finding_text}</div>
            <div class="finding-source">
                Source: {source_name} -
                <a href="{source_url}" target="_blank">View Article</a>
            </div>
        </div>
            """)
        return "".join(html_items)

    def _format_competitor_activity_html(self, competitor_activity: dict) -> str:
        """Format competitor activity as HTML."""
        html_sections = []
        for competitor in sorted(competitor_activity.keys()):
            # Escape competitor name
            competitor_escaped = html.escape(competitor)
            activities = competitor_activity[competitor]
            activity_html = []
            for activity in activities:
                # Escape all untrusted content
                activity_text = html.escape(activity.get('text', ''))
                source_name = html.escape(activity.get('source_name', ''))
                source_url = html.escape(activity.get('source_url', ''), quote=True)

                activity_html.append(f"""
            <div class="activity-item">
                <div class="finding-text">• {activity_text}</div>
                <div class="finding-source">
                    Source: {source_name} -
                    <a href="{source_url}" target="_blank">View Article</a>
                </div>
            </div>
                """)

            html_sections.append(f"""
        <div class="competitor-section">
            <div class="competitor-name">{competitor_escaped}</div>
            {''.join(activity_html)}
        </div>
            """)

        return "".join(html_sections)
